Blotto: 
	javac -classpath coft-1.2.0.jar:commons-csv-1.4.jar:commons-lang3-3.5.jar:commons-logging-1.2.jar:commons-math3-3.6.1.jar:concurrent-1.3.4.jar:csparsej-1.1.1.jar:joptimizer-5.0.0.jar:. Blotto.java
	echo "#!/bin/bash" > Blotto
	echo "java -classpath coft-1.2.0.jar:commons-csv-1.4.jar:commons-lang3-3.5.jar:commons-logging-1.2.jar:commons-math3-3.6.1.jar:concurrent-1.3.4.jar:csparsej-1.1.1.jar:joptimizer-5.0.0.jar:. Blotto \"\$$@\"" >> Blotto
	chmod u+x Blotto